### ISSUE TITLE
Cannot open load file - No such file or directory "dash"

### ISSUE THREAD

**Issue by leifericf** [cjohansen/.emacs.d#7]
Error when starting Emacs:

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "dash")
  require(dash)
  eval-buffer(#<buffer  *load*-113912> nil "/Users/my-username/.emacs.d/settings/setup-package.el" nil t)  ; Reading at buffer position 35
  load-with-code-conversion("/Users/my-username/.emacs.d/settings/setup-package.el" "/Users/my-username/.emacs.d/settings/setup-package.el" nil t)
  require(setup-package)
  eval-buffer(#<buffer  *load*> nil "/Users/my-username/.emacs.d/init.el" nil t)  ; Reading at buffer position 2248
  load-with-code-conversion("/Users/my-username/.emacs.d/init.el" "/Users/my-username/.emacs.d/init.el" t t)
  load("/Users/my-username/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1ff9c7c183f1>) #f(compiled-function () #<bytecode 0x1ff9c7c19c0d>) t)
  command-line()
  normal-top-level()
```

Emacs version (installed via Homebrew):

```
$ emacs --version

GNU Emacs 27.2
Copyright (C) 2021 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

macOS version:

```
$ sw_vers

ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52
```

Dash is installed on my system (version 6.2.2).

**Comment by magnars** [comment]
Dette er bare Christian sin private .emacs.d, så det er nok ikke lagt veldig mye kjærlighet i at andre skal bruke den. Jeg har prøvd å gjøre min litt mer fork-bar, @leifericf.

**Comment by leifericf** [comment]
Takk for info, @magnars!

Hadde faktisk tenkt å legge inn dette issue i min egen fork, for å dokumentere problemet og fiksen for meg selv i fremtiden. Men så laget jeg issuet i source repo istedenfor min fork ved en feiltagelse.

**Comment by magnars** [comment]
Gjorde du `git clone --recursive git://github.com/magnars/.emacs.d.git` da?

**Comment by leifericf** [comment]
Nei, jeg kjørte `git clone git@github.com:leifericf/.emacs.d.git` fra min egen fork av Christian sitt repo. Men jeg skal nå gjøre en fork av ditt repo istedenfor, og kjøre cline med `--recursive`.

**Comment by magnars** [comment]
Det forklarer i hvert fall feilen, ettersom du da ikke har lastet ned submoduler.

**Comment by leifericf** [comment]
Jepp! Jeg innser det nå, overså at det var submoduler. My bad!

**Comment by magnars** [comment]
Kan anbefale å lese README'n. :)

**Comment by leifericf** [comment]
Det skal jeg absolutt gjøre! Har brukt Vim i mange år, og Visual Studio Code til Clojure frem til nå. Men tenkte jeg skal teste ut opplevelsen i Emacs for å sammenligne. Så det er mye nytt å lære seg, og mange feil å begå.

**Comment by magnars** [comment]
Ja, det kan være en tung start, men vel verdt investeringen, mener nå jeg. Det største poenget er at man tar kontroll over sitt eget utviklingsmiljø. Jeg har bygget alle mulige slags features inn i editoren min. "Build your own light saber" :)

**Comment by leifericf** [comment]
Jeg er absolutt en fan av den skolen.

Lærte det når jeg leste "The Pragmatic Programmer" i 2012, men den gang valgte jeg Vim :)
